# 1. DEFINICIÓN DEL BACKEND (Upstream)
# 'gateway-service' es el nombre exacto de tu servicio en docker-compose.yml
upstream gateway_backend {
    server gateway-service:8080;
}

# Nginx Server Block Configuration for Single Page Application (SPA)
server {
    # Listen on port 80 for incoming HTTP traffic inside the container
    listen 80;
    
    # Server hostname matching
    server_name localhost;

    # Docker internal DNS (127.0.0.11 always exists in bridge networks)
    # resolver 127.0.0.11 valid=10s ipv6=off;

    # Backend Routes (Reverse Proxy) 
    location /api/ {
        # ! NOTE: use variable + resolve to force re-resolution
        # set $gateway http://gateway-service:8080;
        # proxy_pass $gateway;

        # Reenvía la petición completa (/api/v1/...) al upstream
        proxy_pass http://gateway_backend;

        # Use 'gateway-service' because that's what the service is called in docker-compose 
        # proxy_pass http://gateway-service:8080;

        # Recommended headers to propagate the client's real IP 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme;

        # Generous timeouts for slow calls
        proxy_connect_timeout 10s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
    }

    # Handle all incoming request routes
    location / {
        # Root directory where compiled static assets (HTML, JS, CSS) are stored
        root /usr/share/nginx/html;
        
        # Default entrypoint files to serve when a directory path is requested
        index index.html index.htm;
        
        # SPA Routing Fallback (React Router / Client-side Routing):
        # 1. $uri   -> Try to serve the exact requested physical file (e.g. /assets/index.js)
        # 2. $uri/  -> Try to serve a matching physical directory
        # 3. /index.html -> If neither exists (e.g. /packages, /vehicles), fallback to index.html 
        #                   so React Router can parse the client-side route natively.
        try_files $uri $uri/ /index.html;
    }
}